### ISSUE TITLE
correct cost estimate for Appendix - 197640 - Tributary to Buck Creek

### ISSUE THREAD

**Issue by NewGraphEnvironment** [NewGraphEnvironment/fish_passage_bulkley_2020_reporting#36]

**Comment by lucy-schick** [comment]
- [x] fix black text on table headings, https://github.com/NewGraphEnvironment/mybookdown-template/issues/50
- [ ] fix table order, referencing is not ordered
- [x] cost estimate issue arising from no road `class` or `surface` in tables used for `my_cost_estimate()`. Just NA

**Comment by lucy-schick** [comment]
Issue was that `recommended_diameter_or_span_meters` was NA in `pscis_phase1.xls`, which meant that `cost_est_1000s` was NA due to https://github.com/NewGraphEnvironment/fish_passage_bulkley_2020_reporting/blob/master/R/0330-tables-phase1-cost-estimate.R#L27C5-L27C92.

Manually fixed in `pscis_phase1.xls` and also had to manually fix in `pscis_rd` object then reburn to `pscis_rd.csv` because `pscis_rd` is built using outdated tables and db connections (https://github.com/NewGraphEnvironment/fish_passage_bulkley_2020_reporting/blob/master/R/0260-extract-rd-cost-mult.R#L87C1-L98C19).  When report builds it just reads in `pscis_rd.csv`. 

fixed with the following code:

```
pscis_rd_test <- pscis_rd |> 
  mutate(recommended_diameter_or_span_meters = if_else(pscis_crossing_id == 197640, 10, recommended_diameter_or_span_meters))


readr::write_csv(pscis_rd_test, file = paste0(getwd(), '/data/extracted_inputs/pscis_rd.csv'))
```
